hyperledger/besu-native

.circleci/config.yml, .gitignore, .gitmodules, build.sh
Initial native build for secp256k1, including circleci config
=> secp256k1: initial build

secp256k1/build.gradle
=> secp256k1: fix env var resolution in publish step

.circleci/config.yml, .gitignore, altbn128/build.gradle, altbn128/gradle.properties, altbn128/sputnikvm_altbn128/Cargo.toml, altbn128/sputnikvm_altbn128/src/lib.rs, altbn128/src/main/java/org/hyperledger/besu/nativelib/altbn128/LibAltbn128.java, build.sh, secp256k1/build.gradle, settings.gradle
Native library for AltBN128 precompiled contract.  Derived from SputnikVM
https://github.com/ETCDEVTeam/sputnikvm/blob/8ce6d085a0773196a198400ca9721e19bd7ed8a0/precompiled/bn128/src/lib.rs
=> AltBN128 Native Library

altbn128/build.gradle
=> altbn128: fix env var resolution in publish step

altbn128/gradle.properties, secp256k1/gradle.properties
=> release v0.1.0

altbn128/gradle.properties, secp256k1/gradle.properties
=> bump version number

.circleci/config.yml, .gitmodules, bls12-381/build.gradle, bls12-381/gradle.properties, bls12-381/src/main/java/org/hyperledger/besu/nativelib/bls12_381/LibEthPairings.java, build.sh, settings.gradle
Add the Matter Labs EIP2537 library to handle BLS12-381 precompiles.
=> Add BLS12-381 library

build.sh
Update secp256k1 to endomorphic version.  40% improvement locally nets
out to 3-5% improvement fully loaded sync on goerli.
Update matter labs to fix BN bug.  Perf is 5x locally nets out to
45% improvement fully loaded sync in goerli (some 1k segments see 
3x improvement)
=> Update dependent libraries

.circleci/config.yml, altbn128/build.gradle, bls12-381/build.gradle, secp256k1/build.gradle
Use github packages.  Currently in addition to bintray.
=> Begin Bintray Exodus

altbn128/build.gradle, bls12-381/build.gradle, secp256k1/build.gradle
Revisie contextUrl for better integration
=> Artifactory contextUrl

altbn128/build.gradle, bls12-381/build.gradle, secp256k1/build.gradle
Use the correct artifactory context url
=> Revise Artifactory Config

.circleci/config.yml, altbn128/build.gradle, bls12-381/build.gradle, build.gradle, secp256k1/build.gradle
Remove bintray and github packages references.
=> Remove Bintray

.github/workflow/repolint.yml, README.md
Add Hyperledger standard repolinter
=> Repolinter

.circleci/config.yml, altbn128/build.gradle, bls12-381/build.gradle, build.sh, secp256k1/build.gradle
Build darwin-arm64 native crypto libraries 
* bump circle-ci Xcode version
* add both x86 and arm64 arch CFLAGS when building on darwin
* bump jna to 5.8.0 
* bump tuweni to 2.0.0
* fix matter-labs/eip1562 build
* submodule updates to latest
* cargo universal binaries for osx:
* bump rust version to support aarch64-apple-darwin
* update circle-ci osx build env to include rust toolchains for x86_64 and aarch64
* target multiple architectures for cargo builds on osx
* use lipo to build universal lib from single-arch artifacts
Fixes #40 
darwin artifacts prior (from arm64):
```
besu-native git:(master) ✗ file secp256k1/build/lib/libsecp256k1.0.dylib
secp256k1/build/lib/libsecp256k1.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
```
darwin artifacts new (from arm64):
```
➜ …
```
=> enable builds native M1/arm64 crypto libs

.circleci/config.yml, .github/workflows/repolinter.yml
Update the CI configuration to use `main` as the default branch.
=> Update CI to main

gradle.properties
Signed-off-by: Lucas Saldanha <lucascrsaldanha@gmail.com>
=> Prepare for 0.4.1-SNAPSHOT

secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1.java
Signatures with their first byte being 0 were incorrectly converted to its native representation. The fix shifts those values one position to the right, in order to convert them back correctly.
Signed-off-by: Daniel Lehrner <daniel@io.builders>
=> Fixed faulty conversion

gradle.properties
besu-native-ec is updated to the latest version to correct the dynamic library resolution on macOS
Signed-off-by: Daniel Lehrner <daniel@io.builders>
=> Fix Besu integration on macOS

gradle.properties
Related to https://github.com/ConsenSys/besu-native-ec/pull/17
=> Release 0.4.2

CHANGELOG.md, gradle.properties
Signed-off-by: Lucas Saldanha <lucascrsaldanha@gmail.com>
=> Release 0.4.3

gradle.properties
Signed-off-by: Lucas Saldanha <lucascrsaldanha@gmail.com>
=> Preparing for next release

altbn128/build.gradle, bls12-381/build.gradle, gradle/wrapper/gradle-wrapper.properties, secp256k1/build.gradle, secp256r1/build.gradle
* Gradle -> 7.4.2
* JNA -> 5.11.0
* guava -> 31.1-jre
* junit -> 4.13.2
* tuweni -> 2.2.0
* assertj -> 3.22.0
=> Upgrade dependencies

secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java
The secp256k1 api depends on some magic values passed into the native
functions.  Move those magic values over to constants
=> Add more static values

.circleci/config.yml
remove former rocketchat notification url config
=> remove defunct rocketchat notification webhook

CHANGELOG.md, gradle.properties
0.5.0 release includes:
* multipoint-ipa 
* arm64-linux support
=> release version for 0.5.0

CHANGELOG.md, gradle.properties
Prepare for next release, 0.5.1-SNAPSHOT
=> Prepare for next release

CHANGELOG.md, gradle.properties
Signed-off-by: Fabio Di Fabio <fabio.difabio@consensys.net>
=> Release 0.6.0

.github/workflows/build.yml
Signed-off-by: Ry Jones <ry@linux.com>
=> Use current labels for native runners

CHANGELOG.md, gradle.properties
=> prepare for 0.6.2

CHANGELOG.md, gradle.properties
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>
=> Prepare release 0.6.2

ipa-multipoint/ipa_multipoint_jni/src/lib.rs
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>
=> offer an additional test to make sure we can call the API repeatidly

gradle.properties
Update the release version to trigger a release.
Signed-off-by: Danno Ferrin <danno.ferrin@swirldslabs.com>
=> Version 0.7.0 release

RELEASE.md, gradle.properties
Update to 0.7.1 snapshot, and add some color to historically how versions have been updated.
Signed-off-by: Danno Ferrin <danno.ferrin@swirldslabs.com>
=> Prepare 0.7.1

.github/workflows/build.yml, gradle.properties
Re-spin on Ubuntu 20.04 and Mac OSX 11.0
=> Release 0.7.1

gradle.properties
Signed-off-by: Danno Ferrin <danno.ferrin@swirldslabs.com>
=> prepare 0.7.2 release

CHANGELOG.md, gradle.properties
=> Release 0.8.0

CHANGELOG.md, gradle.properties
=> Next release 0.8.1

.github/workflows/build.yml, secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/BesuNativeEC.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/KeyRecoveryResult.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/SignResult.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/VerifyResult.java
=> CodeQL fixes

gradle.properties
=> Prepare 0.8.2

CHANGELOG.md, gradle.properties
=> Release 0.8.2

gradle.properties
=> Prepare 0.8.3

CHANGELOG.md, gradle.properties
=> release version 0.8.3

CHANGELOG.md, gradle.properties
=> prepare for 0.8.4-SNAPSHOT

native-build.sh
=> fix native-build.sh update rust version

CHANGELOG.md, gradle.properties
Release 0.8.4 of besu-native libraries
Signed-off-by: Danno Ferrin <danno@numisight.com>
=> Release 0.8.4

gradle.properties
merge this after #171 
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
=> prepare 0.8.6 - next release

.github/workflows/build.yml
See: https://github.com/hyperledger/besu/pull/7173
Cc: @ryjones
=> Use github arm64 runners

CHANGELOG.md, gradle.properties
Release 0.9.0 includes:
* gnark-crypto implementation for EIP-196, EIP-197, EIP-2537
* source and target java 21
* gradle 8.8
=> release version for 0.9.0

CHANGELOG.md, gradle.properties
=> prep for next release version 0.9.1-SNAPSHOT

altbn128/build.gradle, altbn128/src/main/java/org/hyperledger/besu/nativelib/altbn128/LibAltbn128.java, bls12-381/src/main/java/org/hyperledger/besu/nativelib/bls12_381/LibEthPairings.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/AltBN128G1AddPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/AltBN128G1MulPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/AltBN128PairingPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/AltBN128PairingPrecompiledContractTestLegacy.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12G1AddPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12G1MulPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12G1MultiExpPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12G2AddPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12G2MulPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12G2MultiExpPrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12MapFp2ToG2PrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12MapFpToG1PrecompiledContractTest.java, bls12-381/src/test/java/org/hyperledger/besu/nativelib/bls12_381/BLS12PairingPrecompiledContractTest.java, build.gradle, gnark/src/test/java/org/hyperledger/besu/nativelib/gnark/AltBN128G1AddPrecompiledContractTest.java, gnark/src/test/java/org/hyperledger/besu/nativelib/gnark/AltBN128G1MulPrecompiledContractTest.java, gnark/src/test/java/org/hyperledger/besu/nativelib/gnark/AltBN128PairingPrecompiledContractTest.java, secp256k1/build.gradle, secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/BesuNativeEC.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/KeyRecoveryResult.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/SignResult.java, secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/VerifyResult.java, secp256r1/src/test/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1Test.java, settings.gradle
=> cumulative copyright attribution fixes

CHANGELOG.md, gradle.properties
=> prep release next 0.9.2-SNAPSHOT

CHANGELOG.md, gradle.properties
=> Rel next 0.9.3

gradle.properties
=> Rel next 0.9.4 snapshot

CHANGELOG.md, gradle.properties
Release version for 0.9.4
* #184 
* #197
=> release version for 0.9.4

gradle.properties
=> Relnext 0.9.5 snapshot

CHANGELOG.md, gradle.properties
* Optimizations in bn254 ECMUL [#207](https://github.com/hyperledger/besu-native/pull/207)
* Linux aarch64 support for EIP196 constantine [#203](https://github.com/hyperledger/besu-native/pull/203)
=> 0.9.5 release version

gradle.properties
bump to 0.9.6.  Draft until merge of #208
=> bump release version

gradle.properties
bump to 1.0.0-SNAPSHOT, draft while waiting for #219 release version to merge
=> Relnext 1.0.0

gnark/gnark-jni/README.md, gnark/gnark-jni/gnark-eip-196.go, gnark/gnark-jni/gnark-test-data.go
helper for test input generation.  Not exhaustive for all ECC precompiles, but we can add as we need.
=> test data generator / helper for ECC inputs

CHANGELOG.md
Pectra-ready version 1.0 version of besu native.
=> release version 1.0.0

gradle.properties
=> Release 1.0

gradle.properties
=> Next release version 1.0.1 snapshot

CHANGELOG.md, gradle.properties
release 1.1.0, coincide with bls changes in pectra devnet-5:
* https://github.com/ethereum/EIPs/pull/9116
* https://github.com/ethereum/EIPs/pull/8945
=> release version 1.1.0

gradle.properties
=> Relnext 1.1.1

gradle.properties
rev gradle properties, after the release of 1.1.2
=> Relnext 1.1.3-snapshot

gradle.properties
Bump release version to 1.2.1-SNAPSHOT
=> Relnext 1.2.1 snapshot

gradle.properties
reprise of #247 with the missing gradle.properties commit
=> Release 1.2.0 reprise

gradle.properties
=> Reprise relnext 1.2.1-SNAPSHOT 

gradle.properties
=> Relnext 1.2.2 snapshot

CHANGELOG.md, gradle.properties
=> release 1.3.0

gradle.properties
=> Relnext 1.3.1 snapshot

gnark/gnark-jni/gnark-eip-2537.go
`nonMontgomeryMarshalG1` always returned nil, so this PR just removes the extraneous if statements and return argument
=> chore: Remove infallible if statement

gradle.properties
=> Bump to next snapshot release 1.3.2
