- .circleci/config.yml
- build.sh
- secp256k1/build.gradle
- secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java
Includes changes to the CircleCI configs to support building native dependencies across Linux (x86_64), and macOS. Will update in a future PR with support for Linux (ARM32) and Windows.
> Multiplatform build with artifacts publishing to bintray

- secp256k1/build.gradle
Turns out it doesn't require the jnilib.  In fact, it doesn't even search for it.
> MacOSX tweak

- secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java
Add a system property `secp256k1.randomize` that can be set to false.
If not set or if the value is set to a Boolean.parseBoolean true value
then the context is randomized prior to use.  If set to a value that
does not parse to true then no randomization is performed.
> Change secp256k1 context to be randomized by default

- bls12-381/src/main/java/org/hyperledger/besu/nativelib/bls12_381/LibEthPairings.java
- gradle.properties
Ad EIP 196 (BN add/mul) and EIP197 (BN pairing).  Performance is notably
better than the sputnikvm code.
> Add EIP196/197 methods to matterlabs library

- README.md
Signed-off-by: Daniel Lehrner <daniel@io.builders>
Fixes #37 
I added some more commands to the README to initialize the git submodules correctly and how to install Rust
> Updated README.md to add missing steps for the setup

- CHANGELOG.md
- gradle.properties
This version has the fix for native representation of native secp256r1 signatures [#45](https://github.com/hyperledger/besu-native/pull/45)
> Release 0.4.1

- secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java
This uses `java.util.Random.nextBytes` instead of `java.security.SecureRandom.generateSeed` to generate the seed used to "randomize" the secp256k1 context. The later might block indefinitely on some platforms when the OS' RNG runs out of entropy.
`java.util.Random` is a much weaker source of randomness (2^48 cycle, much less under real world conditions due to imperfect seed). It is however sufficient in this case: The context randomization is only used as an additional precaution against side channel attacks in case the compiler ruins the constant time property of the underlying code.
Signed-off-by: Taccat Isid <taccatisid@protonmail.com>
> use non-blocking PRNG to generate secp256k1 context

- secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1.java
- secp256r1/src/test/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1Test.java
_Note from @NicolasMassart (Consensys Customer Support):
This PR if from one of the Consensys customers directly. I removed the internal reference to our ticketing system as it's not useful to HL community as they don't have access. The PR is well referenced in the ticket on our side._
Sometimes the signature components (in that case it was R) are 30-bytes long and both the keys and the signatures are still valid.
The values added in the unit test are taken from one of the actual errors shown in the error logs:
```
2022-01-19 17:39:09.672+00:00 | EthScheduler-Workers-1 | INFO  | PersistBlockTask | Imported #591,672 / 22 tx / 0 om / 784,208 (0.0%) gas / (0x14eb9590af60f2e86d4a617bb34e8de4255b35819cfbb8a1a87dc0cbbc021b21) in 0.065s. Peers: 4
2022-01-19 17:39:10.032+00:00 | …
```
> Padding of the R and S components in case they are smaller than 31 bytes for SECP256r1

- .circleci/config.yml
Update rust versions to 1.62.1 so that ipa-multipoint can compile.
> update rust versions to 1.62.1

- altbn128/build.gradle
- blake2bf/aarch64/makefile
- blake2bf/build.gradle
- blake2bf/src/main/java/org/hyperledger/besu/nativelib/blake2bf/LibBlake2bf.java
- blake2bf/x86_64/blake2b.c
- blake2bf/x86_64/makefile
- bls12-381/build.gradle
- build.sh
- ipa-multipoint/build.gradle
- ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java
- secp256k1/build.gradle
- secp256r1/build.gradle
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>
> Ship both x86 and aarch64 darwin libs

- .gitmodules
- build.sh
Build BLS-12 for linux arm.  Also has the altbn128 libs.
> Build BLS-12 on linux arm

- bls12-381/build.gradle
Copy the eth_pairings.so lib into the jar resources directory.
> Copy linux BLS lib

- build.sh
Benchmarking shows the blake on arm code is slower than the java versions running on arm, so don't build it.
> Disable arm blake2b

- altbn128/build.gradle
- secp256k1/build.gradle
- secp256r1/build.gradle
Restore the generation of the two ECDSA libs in the new darwin-<arch> format.
> Restore Mac ECDSA libs

- CHANGELOG.md
- gradle.properties
0.6.1 release includes:
* Update to jna 5.12.1
* Add linux arm64 build of bls12-381 
* Restrict builds of blake2f to x86-64 
Signed-off-by: garyschulte <garyschulte@gmail.com>
> 0.6.1 release version

- ipa-multipoint/ipa_multipoint_jni/src/lib.rs
- ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>
Instead of using 4 arguments, allow to use n arguments for the commit method.
> support computing proof with n arguments

- altbn128/build.gradle
- blake2bf/build.gradle
- bls12-381/build.gradle
- ipa-multipoint/build.gradle
- secp256k1/build.gradle
- secp256r1/build.gradle
Signed-off-by: Mustafa Uzun <mustafa.uzun@limechain.tech>
Add java modules support:
./bls12-381 - org.hyperledger.besu.native.bls12_381
./secp256k1 - org.hyperledger.besu.native.secp256k1
./secp256r1 - org.hyperledger.besu.native.secp256r1
./altbn128 - org.hyperledger.besu.native.altbn128
./blake2bf - org.hyperledger.besu.native.blake2bf
./ipa-multipoint - org.hyperledger.besu.native.ipa.multipoint
> Java modules support

- .github/workflows/build.yml
Github Actions recently migrated the major versions of ubuntu and macosx for its standard builders. This "stealth" upgrade made the 0.7.0 release unsuitable for CI use as it started depending on newer versions
of glibc.
Fix the versions of ubuntu and macos to pre-october values.
> Use specific CI OS versions.

- altbn128/build.gradle
- arithmetic/build.gradle
- blake2bf/build.gradle
- bls12-381/build.gradle
- gnark/build.gradle
- gradle.properties
- ipa-multipoint/build.gradle
- secp256k1/build.gradle
- secp256r1/build.gradle
Migrate all maven coordinates that were `.native.` to `.nativelib.`. The old coordinate name presented problems in some auto-module systems for the JPMS.
> Change coordinates from native to nativelib

- .github/workflows/build.yml
- blake2bf/src/test/java/org/hyperledger/besu/nativelib/blake2bf/LibBlake2bfTest.java
Since the native blake2bf implementation is slower than the java implementation on arm64, it is not being built:
https://github.com/hyperledger/besu-native/blob/main/build.sh#L69-L76
Ignore this test if we are running on arm64.  Tested on OSX
edit: Also address CI breakage with this PR.  
fixes #110
> disable blake tests on arm64

- ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java
Javadoc was failing because of HTML-incompatible characters.
They were removed
> FIX: javadoc problems, removes <-> chars

- gnark/gnark-jni/gnark-jni.go
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnark.java
- gnark/src/test/java/org/hyperledger/besu/nativelib/gnark/LibGnarkTest.java
The current PR adds supports for the MiMC hash function, but on the BLS12-377 scalar's field (not to be confused with BLS12-381). The implementation is - as for its BN254 counterpart - imported from gnark's. The PR keeps support for the BN254's implementation which is used by Shomei as of now. The implementation 
In more details:
- Renames `computeMiMC` to `computeMiMC254` to make the naming more specific. This can be reverted if deemed useful during the review as this introduces a breaking change.
- Extends the LibGnark class to also provide `computeMiMCBls12377`
- Adds test-cases on the Java side to check the hashes are consistent with what we get on go. The test-vectors used for the testing are the same as the one used for the Bn254 counterpart.
> Add support for MiMC on BLS12-377's scalar field

- ipa-multipoint/ipa_multipoint_jni/Cargo.toml
This fixes the commit for verkle-trie, since pointing to master can make compiles non-deterministic.
This will change soon to using ffi_interface, though while that PR is not merged this is a fix.
> fix: fix the commit for verkle dependency

- ipa-multipoint/ipa_multipoint_jni/src/lib.rs
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/CommitRootTest.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/PedersenCommitmentTest.java
Switching to LE bytes paired with https://github.com/hyperledger/besu-verkle-trie/pull/36 .
Closes https://github.com/hyperledger/besu-native/issues/126
> chore(ipa-multipoint): switch to LE bytes

- ipa-multipoint/ipa_multipoint_jni/src/lib.rs
- ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/PedersenCommitmentTest.java
Switching to uncompressed commitments and adding a groupToField method.
Closes https://github.com/hyperledger/besu-native/issues/130 
Closes https://github.com/hyperledger/besu-native/issues/128
This is paired with https://github.com/hyperledger/besu-verkle-trie/pull/37
> add groupToField and return uncompressed serialized commitments

- ipa-multipoint/ipa_multipoint_jni/Cargo.toml
- ipa-multipoint/ipa_multipoint_jni/src/lib.rs
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java
updates the rust verkle dependency to the latest version and modifies the code to match.
- PedersenHash has changed internally to use MapToScalarField
- Methods now take a context and not a committer to make calling them easier.
> chore!: Updates rust-verkle dependency

- ipa-multipoint/ipa_multipoint_jni/src/lib.rs
- ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java
- ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java
Once https://github.com/hyperledger/besu-verkle-trie/pull/43 is merged, the `pedersenHash` method will no longer be needed.
This PR removes it from the API.
> chore!: Removes pedersenHash method

- altbn128/build.gradle
- secp256k1/build.gradle
- secp256r1/build.gradle
Undiscovered fallout from the upgrade to gradle 8.8 resulted in a failure of the publish task (which isn't executed in the CI pipeline normally)
this PR fixes the dep issue for a few gradle projects
> gradle upgrade errata: fix implied deps error 

- arithmetic/build.gradle
- bls12-381/build.gradle
- gnark/build.gradle
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkEIP196.java
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkEIP2537.java
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkUtils.java
- ipa-multipoint/build.gradle
- secp256r1/build.gradle
Remove tuweni as a runtime dependency for gnark-crypto, back to testImplementation dependency.  Also, bump tuweni dep to tmio.
In besu we have to specifically exclude this dependency from the gnark dep to prevent conflicts with besu's version of tuweni.
> 0.9.0 errata, move to tmio for tuweni dep

- CHANGELOG.md
- gradle.properties
Release 0.9.1, fix minor errata in 0.9.0 release relating to gnark-crypto deps and an eip-196 edge case
> release 0.9.1

- CHANGELOG.md
- gradle.properties
minor release addressing malformed inputs for gnark-crypto impl of EIP-196
> release 0.9.2

- CHANGELOG.md
- gradle.properties
release 0.9.3 
* remove long-deprecated altbn128 [#192](https://github.com/hyperledger/besu-native/pull/192)
* fix eip-196 point padding in gnark-crypto [#191](https://github.com/hyperledger/besu-native/pull/191)
> release 0.9.3

- .github/workflows/build.yml
Recently same version published and caused issues for the downstream applications with checksum changes. Added GitHub step check whether the version configured has been released previously. This will prevent overriding existing releases
fixes consensys/protocol-misc#937
> Check released version and configured version

- .github/workflows/build.yml
Reverts hyperledger/besu-native#196
We need to revisit this check since the way it is written currently prevents releasing besu-native at all
> Revert "Check released version and configured version"

- .github/workflows/build.yml
- build.sh
- constantine/build.gradle
- constantine/jna_ethereum_evm_precompiles.c
- constantine/jna_ethereum_evm_precompiles.h
- constantine/src/main/java/org/hyperledger/besu/nativelib/constantine/LibConstantineEIP196.java
- constantine/src/test/java/org/hyperledger/besu/nativelib/constantine/ConstantineEIP196G1AddTest.java
- constantine/src/test/java/org/hyperledger/besu/nativelib/constantine/ConstantineEIP196G1MulTest.java
- constantine/src/test/java/org/hyperledger/besu/nativelib/constantine/ConstantineEIP196PairingCheckTest.java
- constantine/src/test/java/org/hyperledger/besu/nativelib/constantine/LibConstantineEIP196Test.java
- native-build.sh
Fixes https://github.com/hyperledger/besu-native/issues/198
> Linux aarch64 support for EIP196 constantine

- .github/workflows/build.yml
Workflow checks whether the configured non snapshot version has been published already to prevent re-publish same version
> Prevent publishing same version

- .gitignore
- gnark/gnark-jni/gnark-eip-196.go
Optimizations for ecmul in gnark-crypto eip196 imple for ECMUL:
* use .Double() when ecmul when scalar == 2 
* if point is infinity encoding, just return infinity
> Optimizations in bn254 ECMUL

- gnark/gnark-jni/gnark-eip-2537.go
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkEIP2537.java
Implement gnark MultiExp for g1/g2 MSM, using default degree of parallelism.
> add parallel g1/g2 msm gnark-crypto impl

- CHANGELOG.md
- gradle.properties
Release 0.9.7
* bump to gnark-crypto 0.14.0 relase version [#212](https://github.com/hyperledger/besu-native/pull/212)
* use multiExp with configurable parallelism in gnark-crypto bls12 MSM precompiles [#217](https://github.com/hyperledger/besu-native/pull/217)
> Release 0.9.7

- gnark/gnark-jni/go.mod
- gnark/gnark-jni/go.sum
Use [subgroup performance improvement](https://github.com/Consensys/gnark-crypto/pull/557) in gnark-crypto main.
All of the besu performance and correctness tests for BLS12 have been using this commit since late October.  This PR aims to git it into main ahead of pectra devnet-5, which will have updated bls spec implementation
> Use improved subgroup checks from gnark-crypto

- gnark/src/test/java/org/hyperledger/besu/nativelib/gnark/BLS12G1MultiExpComparisonTest.java
- gnark/src/test/java/org/hyperledger/besu/nativelib/gnark/BLS12G2MultiExpComparisonTest.java
Ignore expensive MSM comparison tests.  These were left enabled by accident in #226
> Ignore msm comparison tests

- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkEIP2537.java
bugfix, set the output length for both pippengers and non-pip MSM result. regression from #226
> Ensure output length is set for low pair count MSM

- CHANGELOG.md
- gradle.properties
bug fix release
* Ensure output length is set for low pair count MSM [#231](https://github.com/hyperledger/besu-native/pull/231)
> Bugfix release 1.1.1

- CHANGELOG.md
- gradle.properties
Release version for 1.1.2
Ubuntu 20.04 glibc support release
* revert to ubuntu 20.04 for ci builds, update to gha 4.x for upload and download artifacts [#236](https://github.com/hyperledger/besu-native/pull/236)
> release 1.1.2 version

- CHANGELOG.md
- arithmetic/build.gradle
- blake2bf/src/test/java/org/hyperledger/besu/nativelib/blake2bf/LibBlake2bfTest.java
- build.sh
- constantine/build.gradle
- gnark/build.gradle
- ipa-multipoint/build.gradle
- secp256k1/build.gradle
- secp256r1/build.gradle
- settings.gradle
Allow besu-native to build on linux-gnu-riscv64 , ignore constantine and blake2.
This PR just adds the build targets, it does not add CI for riscv64.  The resulting merge will not automatically create a riscv64 compatible besu-native release.
Tested on bpif3 with Armbian
> initial pass at adding riscv64 support in besu-native

- .github/workflows/build.yml
- CHANGELOG.md
- README.md
- arithmetic/build.gradle
- arithmetic/src/main/java/org/hyperledger/besu/nativelib/arithmetic/LibArithmetic.java
- blake2bf/build.gradle
- blake2bf/src/main/java/org/hyperledger/besu/nativelib/blake2bf/LibBlake2bf.java
- build.sh
- common/build.gradle
- common/src/main/java/org/hyperledger/besu/nativelib/common/BesuNativeLibraryLoader.java
- constantine/build.gradle
- constantine/src/main/java/org/hyperledger/besu/nativelib/constantine/LibConstantineEIP196.java
- constantine/src/main/java/org/hyperledger/besu/nativelib/constantine/LibConstantineEIP2537.java
- gnark/build.gradle
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnark.java
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkEIP196.java
- gnark/src/main/java/org/hyperledger/besu/nativelib/gnark/LibGnarkEIP2537.java
- ipa-multipoint/build.gradle
- ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java
- native-build.sh
- secp256k1/build.gradle
- secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java
- secp256r1/build.gradle
- secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1.java
- secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/BesuNativeEC.java
- settings.gradle
Use explict paths based on arch in besu-native during the library builds, and during library loading.  We are still using JNA for jna libraries, and jni for jni libraries.  However we are using conformed arch names to publish and find native libs.  This should resolve the OSTYPE and OSARCH naming problems that seem to plague linux distributions especially.
fixes #242 
is blocking [#8432](https://github.com/hyperledger/besu/issues/8342)
Tested on:
* Mac Os 15.3.1 on M2max
* Ubuntu 24.04 on x86_64
* Pop! OS linux 22.04 x86_64
* Armbian Linux 24.8.4 on riscv64
* Armbian Linux 24.5.5 on arm64
Build fails on:
* Mac Os 10.15.7 on X86 (❌ build fails, OS toolchain is too old to know how to build a lipo lib)
> Refactor of library loading to remove platform/arch naming differences

- .github/workflows/build.yml
- CHANGELOG.md
- README.md
- build.sh
Constantine has significant improvements in the [0.2.0 release](https://github.com/mratsim/constantine/releases/tag/v0.2.0)
Additionally, package managers have moved to 2.2.x versions of nim, which the v0.1.0 release of Constantine cannot compile against.  Since v0.2.0  is compatible with the latest nim compiler releases, it makes sense to update both constantine and nim.
* bump constantine submodule to [v0.2.0](https://github.com/mratsim/constantine/releases/tag/v0.2.0)
* bump choosenim nim compiler downloads to [2.2.2](https://github.com/nim-lang/Nim/releases/tag/v2.2.2)
* bump linux-arm64 nightly build of nim to 2.2.2 version, sha matched to 2.2.2 release tag version
* updates GHA CI pipeline nim version to 2.2.2
* update README.md with nim version requirements
* local build problem …
> Update constantine to v0.2.0

- CHANGELOG.md
Release 1.2.0 to support pectra mainnet.
Besu has a hard dependency on besu-native for pectra hardfork.  This release makes library loading more robust across a variety of platforms
> release 1.2.0

- common/build.gradle
Add common artifact publishing.  The initial intent for common was for it to be included within the individual native artifacts.  However, in order to prevent class duplication, common should be published as an artifact that can be picked up via transitive dependencies.
Also changes the artifact name to besu-native-common to avoid naming collisions
> Add artifactoryPublishing to common 

- CHANGELOG.md
- gradle.properties
Add besu-native-common to the list of published packages in CI
Errata release
* include besu-native-common in published packages [#252](https://github.com/hyperledger/besu-native/pull/252)
> Release 1.2.1 - Errata

- gnark/gnark-jni/gnark-eip-196.go
- gnark/gnark-jni/gnark-eip-2537.go
> chore: Simplify point decoding logic

- gnark/gnark-jni/gnark-eip-2537.go
This essentially outlines the one liner method into a CopyBytes and PtrOffset method, since it was not clear at first, what was being memcopied
> chore: Outline C.memcpy method

- secp256r1/build.gradle
- secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1.java
- secp256r1/src/main/java/org/hyperledger/besu/nativelib/secp256r1/besuNativeEC/BesuNativeEC.java
- secp256r1/src/test/java/org/hyperledger/besu/nativelib/secp256r1/LibSECP256R1Test.java
Adds the overload from besu-native-ec for p256_verify_malleated_signature
motivation: support for [EIP-7951](https://github.com/ethereum/EIPs/pull/9833/files?short_path=e3d4e97#diff-e3d4e9768cba978506e431cac1b9198302825e58170366b0fad5229f6fb90030)
related to [issue 8605](https://github.com/hyperledger/besu/issues/8605)
related to [pr 8750](https://github.com/hyperledger/besu/pull/8750)
> Enable malleable signature verification for secp256r1

- secp256k1/build.gradle
Bug introduced by https://github.com/hyperledger/besu-native/pull/277
> Fix lib copy paths for new k1_ecrecover libs

- .gitmodules
This makes it easier to build besu-native on a benchmarking machine that might not have a git ssh key setup for example
> [MINOR] Don't force ssh on besu-native builders
